CREATE TABLE "KYC_UGA"."OAUTH_REFRESH_TOKEN" 
   (	"TOKEN_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"AUTHENTICATION" BLOB, 
	"TOKEN" BLOB, 
	 PRIMARY KEY ("TOKEN_ID")
   )
      
   
  CREATE TABLE "KYC_UGA"."OAUTH_ACCESS_TOKEN" 
   (	"TOKEN_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"AUTHENTICATION" BLOB, 
	"AUTHENTICATION_ID" VARCHAR2(255 CHAR), 
	"CLIENT_ID" VARCHAR2(255 CHAR), 
	"REFRESH_TOKEN" VARCHAR2(255 CHAR), 
	"TOKEN" BLOB, 
	"USER_NAME" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("TOKEN_ID")
   )  ;