Insert into KYC_UGA.OAUTH_CLIENT_DETAILS 
(CLIENT_ID,ACCESS_TOKEN_VALIDITY,ADDITIONAL_INFORMATION,AUTHORITIES,AUTHORIZED_GRANT_TYPES,AUTOAPPROVE,CLIENT_SECRET,REFRESH_TOKEN_VALIDITY,RESOURCE_IDS,SCOPE,WEB_SERVER_REDIRECT_URI,DEVICE_ID)
values 
('ani',45000,null,'ROLE_ADMIN','client_credentials,authorization_code,implicit,password,refresh_token','1','$2a$11$MgWCIu2vepR1e7C02DoH5OasUEhBoZYAohWw9gaSVMJyMg9Z7G0nW',45000,'KYC','trust,read,write',null,null);

Insert into KYC_UGA.USERS 
(USER_ID,CREATED_BY,CREATED_ON,DELETE_FLAG,STATUS_FLAG,UPDATED_BY,UPDATED_ON,VERSION,AGENT_ID,IS_BULK_ENABLED,DEVICE_ID,DEVICE_TYPE,ENABLED,FAILURE_REASON,LAST_LOGIN,LOGIN_DEVICE_ID,PASSWORD,PWD_CREATED_ON,PWD_EXPIRE_IN,USER_NAME) 
values 
(1,null,null,'1','0',null,null,1,11,'1','ani',null,null,null,null,null,'$2a$11$MgWCIu2vepR1e7C02DoH5OasUEhBoZYAohWw9gaSVMJyMg9Z7G0nW',null,null,'ani');

Insert into KYC_UGA.ROLE 
(ROLE_ID,CREATED_BY,CREATED_ON,DELETE_FLAG,STATUS_FLAG,UPDATED_BY,UPDATED_ON,VERSION,DESCRIPTION,ROLE_NAME,USER_ROLE_NAME)
values 
(21,null,null,null,null,null,null,0,'ADMIN USER','ADMIN','ROLE_ADMIN');

Insert into KYC_UGA.USER_ROLES 
(USER_ID,ROLE_ID) 
values 
(1,21);
